version: '3.8'

services:
   web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/code
      ports:
         - 8000:8000
      depends_on:
         - db
      restart: "on-failure"
      env_file:
         ./.env


#      environment:
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=postgres
#         - POSTGRES_DB=bookstore
#         - POSTGRES_HOST=db
#         - POSTGRES_PORT=5432

   db:
      image: library/postgres:14-alpine
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      env_file:
         ./.env.db

volumes:
   postgres_data:
